
package cl.bicevida.ws.service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.0
 * 2017-10-17T10:20:33.322-03:00
 * Generated source version: 3.2.0
 */

@WebFault(name = "Exception", targetNamespace = "http://service.ws.bicevida.cl/")
public class Exception_Exception extends java.lang.Exception {
    
    private cl.bicevida.ws.service.Exception exception;

    public Exception_Exception() {
        super();
    }
    
    public Exception_Exception(String message) {
        super(message);
    }
    
    public Exception_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public Exception_Exception(String message, cl.bicevida.ws.service.Exception exception) {
        super(message);
        this.exception = exception;
    }

    public Exception_Exception(String message, cl.bicevida.ws.service.Exception exception, Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public cl.bicevida.ws.service.Exception getFaultInfo() {
        return this.exception;
    }
}
