
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package cl.bicevida.ws.service;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.0
 * 2017-10-17T10:20:33.337-03:00
 * Generated source version: 3.2.0
 * 
 */

@javax.jws.WebService(
                      serviceName = "PagosYAportesWS",
                      portName = "PagosyAportesPort",
                      targetNamespace = "http://service.ws.bicevida.cl/",
                      wsdlLocation = "file:/C:/Users/gustavo.riquelmeg/workspace/bv-historial-pagos-y-aportes/src/main/resources/wsdl/PagosYAportesPort.wsdl",
                      endpointInterface = "cl.bicevida.ws.service.PagosyAportes")
                      
public class PagosyAportesPortImpl implements PagosyAportes {

    private static final Logger LOG = Logger.getLogger(PagosyAportesPortImpl.class.getName());

    /* (non-Javadoc)
     * @see cl.bicevida.ws.service.PagosyAportes#getPagosYAportes(java.lang.String rutDv, java.lang.String poliza, java.lang.String fechaDesde, java.lang.String fechaHasta)*
     */
    public cl.bicevida.ws.service.ResponseServiceTO getPagosYAportes(java.lang.String rutDv, java.lang.String poliza, java.lang.String fechaDesde, java.lang.String fechaHasta) throws PagosYAportesSoapException   { 
        LOG.info("Executing operation getPagosYAportes");
        System.out.println(rutDv);
        System.out.println(poliza);
        System.out.println(fechaDesde);
        System.out.println(fechaHasta);
        try {
            cl.bicevida.ws.service.ResponseServiceTO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new PagosYAportesSoapException("PagosYAportesSoapException...");
    }

    /* (non-Javadoc)
     * @see cl.bicevida.ws.service.PagosyAportes#getGlosa(java.lang.String rutDv, java.lang.String numeroContrato)*
     */
    public cl.bicevida.ws.service.ResponseGlosa getGlosa(java.lang.String rutDv, java.lang.String numeroContrato) throws Exception_Exception   { 
        LOG.info("Executing operation getGlosa");
        System.out.println(rutDv);
        System.out.println(numeroContrato);
        try {
            cl.bicevida.ws.service.ResponseGlosa _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new Exception_Exception("Exception...");
    }

}
